apiVersion: kode.jacero.io/v1alpha1
kind: KodeClusterTemplate
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: kodeclustertemplate-webtop-sample
spec:
  envoyProxyRef:
    kind: EnvoyProxyClusterConfig
    name: envoyproxyclusterconfig-sample
  type: webtop
  image: lscr.io/linuxserver/webtop:latest
  tz: "Europe/Stockholm"
  puid: 1000
  pgid: 1000
  defaultHome: /config
