---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: envoyproxyconfigs.kode.jacero.io
spec:
  group: kode.jacero.io
  names:
    kind: EnvoyProxyConfig
    listKind: EnvoyProxyConfigList
    plural: envoyproxyconfigs
    singular: envoyproxyconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: EnvoyProxyConfig is the Schema for the envoyproxyconfigs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: EnvoyProxyConfigSpec defines the desired state of EnvoyProxyConfig
            properties:
              authType:
                description: AuthType is the type of authentication to use
                enum:
                - basic
                type: string
              clusters:
                description: Clusters is a list of Envoy clusters
                items:
                  properties:
                    connect_timeout:
                      description: ConnectTimeout is the timeout for connecting to
                        the cluster
                      type: string
                    lb_policy:
                      description: LbPolicy is the load balancing policy for the cluster
                      type: string
                    load_assignment:
                      description: LoadAssignment is the load assignment for the cluster
                      properties:
                        cluster_name:
                          description: ClusterName is the name of the cluster
                          minLength: 1
                          type: string
                        endpoints:
                          description: Endpoints is a list of endpoints
                          items:
                            properties:
                              lb_endpoints:
                                description: LbEndpoints is the load balancer endpoints
                                items:
                                  properties:
                                    endpoint:
                                      description: Endpoints is a list of endpoints
                                      properties:
                                        address:
                                          description: Address is the address of the
                                            load balancer endpoint
                                          properties:
                                            socket_address:
                                              description: SocketAddress is the socket
                                                address
                                              properties:
                                                address:
                                                  description: Address is the address
                                                    of the socket
                                                  type: string
                                                port_value:
                                                  description: PortValue is the port
                                                    of the socket
                                                  type: integer
                                              required:
                                              - address
                                              - port_value
                                              type: object
                                          required:
                                          - socket_address
                                          type: object
                                      required:
                                      - address
                                      type: object
                                  required:
                                  - endpoint
                                  type: object
                                type: array
                            required:
                            - lb_endpoints
                            type: object
                          type: array
                      required:
                      - cluster_name
                      - endpoints
                      type: object
                    name:
                      description: Name is the name of the cluster
                      minLength: 1
                      type: string
                    type:
                      description: Type is the type of the cluster
                      type: string
                    typed_extension_protocol_options:
                      description: TypedExtensionProtocolOptions is a map of typed
                        extension protocol options
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  required:
                  - connect_timeout
                  - lb_policy
                  - load_assignment
                  - name
                  - type
                  type: object
                type: array
              httpFilters:
                description: HTTPFilters is a list of Envoy HTTP filters to be applied
                items:
                  description: HTTPFilter represents an individual HTTP filter configuration
                  properties:
                    name:
                      description: Name is the name of the HTTP filter
                      minLength: 1
                      type: string
                    typed_config:
                      description: |-
                        TypedConfig is the typed configuration for the HTTP filter
                        It is intentionally the same as the Envoy filter's typed_config field to make it easier to copy-paste
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  required:
                  - name
                  - typed_config
                  type: object
                type: array
              image:
                default: envoyproxy/envoy:v1.30-latest
                description: Image is the Docker image for the Envoy proxy
                minLength: 1
                type: string
            required:
            - image
            type: object
          status:
            description: EnvoyProxyConfigStatus defines the observed state of EnvoyProxyConfig
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
